### ISSUE TITLE
any other type of queries supported? Timestamp?

### ISSUE THREAD

**Issue by itheodoridis** [mcapra/nagios-nlsexport#2]
Hello. 
I tried using your tool (thank you so much for your work) and I got as far as this (as working example):
java -jar nlsexport.jar -host=localhost -date_start=2017.09.19 -date_end=2017.09.19 -output_path=/root/logs/ -output_format=csv -query=' { "query" : { "query_string" : { "query" : "10.132.1.5" } } } '
which will filter the results getting only those who correspond to that string (10.132.1.5) for that day.
I also hoped to get only a certain time range (to get data only in a certain timerange let's say from 7:50 am to 08:00 am). 
I figured this is Elastic Search syntax (you said so in the help message) so I looked that up and came up with the range query, take a look at these two pages which discuss the timestamp and nested queries.
Is there a chance to make that happen here too? Can I help with testing if that is not supported? 
Thanks again.
https://www.elastic.co/guide/en/elasticsearch/guide/current/_ranges.html 
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-nested-query.html
Ioannis Theodoridis
itheodori@gmail.com

**Comment by mcapra** [comment]
It would depend on how you're parsing your log data. If it's just for a single day, you should be able to pass a unix timestamp of the time (in UTC) in a range filter like so:

```
{
	"query": {
		"filtered": {
			"query": {
				"bool": {
					"should": [{
							"query_string": {
								"query": "*"
							}
						}
					]
				}
			},
			"filter": {
				"bool": {
					"must": [{
							"range": {
								"@timestamp": {
									"from": 1506042515000,
									"to": 1506046115000
								}
							}
						}
					]
				}
			}
		}
	}
}
```

Though if you wanted to say something like "show me 07:00 to 10:00 for the month of September" you would need to be parsing out the hour of the day into a separate field I would think (and querying on that). Or applying some very sophisticated/lengthy queries.

As this question pertains mostly to the structure of ElasticSearch queries, I would suggest taking a trip to the Elastic community forums for further discussion:
https://discuss.elastic.co/

**Comment by itheodoridis** [comment]
Thank's a million Matt! 
That was enough for me to go on and get what I needed, although I will probably continue looking into Elastic Search (the url mentioned was noted as well).
So here is a working example:
java -jar nlsexport.jar -host=localhost -date_start=2017.09.21 -date_end=2017.09.22 -output_path=/root/logs/ -output_format=csv -query=' {  "query": {
            "filtered": {
              "query": {
                "query_string": {
                  "query": "*"
                }
              },
              "filter": {
                "bool": {
                  "must": [
                    {
                      "range": {
                        "@timestamp": {
                          "from": 1505995953118,
                          "to": 1506013256344
                        }
                      }
                    },
                    {
                      "fquery": {
                        "query": {
                          "query_string": {
                            "query": "host = 10.132.1.*"
                          }
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
	} '

I hope more people get to use it!
Again thanks for your great work!
Ioannis.
